## Practice 1: Creating DataFrames and Series

**Q1.** Create a Pandas Series from a list of numbers: `[10, 20, 30, 40, 50]`.

In [14]:
pip install pandas

Requirement already satisfied: pandas in c:\Users\pc\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.0.5)
Requirement already satisfied: numpy>=2.3.3 in c:\Users\pc\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.5.2)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\pc\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\pc\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in C:\Users\pc\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [15]:
import pandas as pd
s=pd.Series([10,20,30,40])

**Q2.** Create a Pandas DataFrame from the following dictionary:
```python
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['New York', 'Los Angeles', 'Chicago']
}
df=pd.dataframe(data)
print(df)

In [16]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['New York', 'Los Angeles', 'Chicago']
}
# Write your code here
df=pd.DataFrame(data)
print(df)

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

## Practice 2: Inspecting Data

**Q3.** Given the DataFrame `df`, display the first 3 rows.
```python
import pandas as pd
import numpy as np
df = pd.DataFrame(np.random.randn(10, 4), columns=['A', 'B', 'C', 'D'])
```

In [18]:
import pandas as pd
import numpy as np
df2 = pd.DataFrame(np.random.randn(10, 4), columns=['A', 'B', 'C', 'D'])
# Write your code here
print(df2.iloc[0:3])

          A         B         C         D
0  1.966360 -0.517293  0.245892 -0.290446
1 -0.866739 -1.261967  1.043534 -0.180840
2 -1.336013 -1.107222 -1.473948  1.108380

**Q4.** Print the shape and column names of the DataFrame `df2`.

In [22]:
# Write your code here
print(df2.shape)
print(df2.columns)

(10, 4)
Index(['A', 'B', 'C', 'D'], dtype='str')

## Practice 3: Selecting and Filtering

**Q5.** Select the column 'Age' from the DataFrame created in Q2 (`df`).

In [23]:
# Write your code here
print(df["Age"])

0    25
1    30
2    35
Name: Age, dtype: int64

**Q6.** Filter the DataFrame `df` from Q2 to show only rows where 'Age' is greater than 28.

In [24]:
# Write your code here
print(df[df["Age"]>28])

      Name  Age         City
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

## Practice 4: Handling Missing Data

**Q7.** Given the following DataFrame with missing values, fill the missing values with 0.
```python
import numpy as np
import pandas as pd
df_nan = pd.DataFrame({'A': [1, np.nan, 3], 'B': [4, 5, np.nan]})
```

In [31]:
import numpy as np
import pandas as pd
df_nan = pd.DataFrame({'A': [1, np.nan, 3], 'B': [4, 5, np.nan]})
# Write your code here
df_filled=df_nan.fillna(0)
print(df_filled)

     A    B
0  1.0  4.0
1  0.0  5.0
2  3.0  0.0

**Q8.** Drop the rows containing any missing values in `df_nan`.

In [32]:
# Write your code here
df_nan.dropna()

     A    B
0  1.0  4.0

## Practice 5: Grouping and Aggregation

**Q9.** Group the following DataFrame by 'Department' and calculate the mean salary.
```python
data = {
    'Department': ['IT', 'HR', 'IT', 'Finance', 'HR'],
    'Salary': [60000, 50000, 70000, 80000, 55000]
}
df_emp = pd.DataFrame(data)
```

In [54]:
data = {
    'Department': ['IT', 'HR', 'IT', 'Finance', 'HR'],
    'Salary': [60000, 50000, 70000, 80000, 55000]
}
df_emp = pd.DataFrame(data)
df_emp.groupby("Department")["Salary"].mean()

Department
Finance    80000.0
HR         52500.0
IT         65000.0
Name: Salary, dtype: float64

## Practice 6: Adding and Removing Columns

**Q10.** Add a new column 'Bonus' to `df_emp` which is 10% of the 'Salary'.

In [36]:
# Write your code here
df_emp["Bonus"]=df_emp["Salary"] * 0.70
print(df_emp)

  Department  Salary    Bonus
0         IT   60000  42000.0
1         HR   50000  35000.0
2         IT   70000  49000.0
3    Finance   80000  56000.0
4         HR   55000  38500.0

**Q11.** Drop the 'Bonus' column from `df_emp`.

In [38]:
# Write your code here
df_emp.drop(columns=["Bonus"])

  Department  Salary
0         IT   60000
1         HR   50000
2         IT   70000
3    Finance   80000
4         HR   55000

## Practice 7: Applying Functions

**Q12.** Apply a function or a lambda to convert the 'Department' names to lowercase in `df_emp`.

In [56]:
df_emp["Department"]=df_emp["Department"].apply(lambda x:x.lower())

## Practice 8: Merging and Joining

**Q13.** Create a DataFrame `df_dept` with columns `Department` and `Manager` mapping 'IT' to 'Alice', 'HR' to 'Bob', and 'Finance' to 'Charlie'. Merge it with `df_emp` (from Practice 5) using a left join.

In [41]:
df_dept = pd.DataFrame({'Department': ['IT', 'HR', 'Finance'], 'Manager': ['Alice', 'Bob', 'Charlie']})
# Write your code here
merged=pd.merge(df_dept,df_emp,on="Department",how="left")
print(merged)

  Department  Manager  Salary    Bonus
0         IT    Alice   60000  42000.0
1         IT    Alice   70000  49000.0
2         HR      Bob   50000  35000.0
3         HR      Bob   55000  38500.0
4    Finance  Charlie   80000  56000.0

## Practice 9: Pivot Tables

**Q14.** Create a pivot table from the merged DataFrame that shows the total (sum) and average (mean) salary for each manager.

In [44]:
# Write your code here
pivot=merged.pivot_table(values="Salary",index="Department",aggfunc=["mean", "sum"])
print(pivot)

               mean     sum
             Salary  Salary
Department
Finance     80000.0   80000
HR          52500.0  105000
IT          65000.0  130000

## Practice 10: Advanced Data Manipulation

**Q15.** Given a DataFrame with sales data, calculate the rolling 3-day average of 'Revenue'.
```python
sales_data = {
    'Date': pd.date_range(start='2023-01-01', periods=10, freq='D'),
    'Product': ['A', 'B', 'A', 'B', 'A', 'A', 'B', 'B', 'A', 'B'],
    'Revenue': [100, 200, 150, 250, 300, 250, 100, 150, 200, 300]
}
df_sales = pd.DataFrame(sales_data)
```

In [ ]:
sales_data = {
    'Date': pd.date_range(start='2023-01-01', periods=10, freq='D'),
    'Product': ['A', 'B', 'A', 'B', 'A', 'A', 'B', 'B', 'A', 'B'],
    'Revenue': [100, 200, 150, 250, 300, 250, 100, 150, 200, 300]
}
df_sales = pd.DataFrame(sales_data)
# 
df_sales["Rolling_Avg_3D"]=df_sales["Revenue"].rolling(window=3).mean()
print(df_sales)

        Date Product  Revenue  Rolling_Avg_3D
0 2023-01-01       A      100             NaN
1 2023-01-02       B      200             NaN
2 2023-01-03       A      150      150.000000
3 2023-01-04       B      250      200.000000
4 2023-01-05       A      300      233.333333
5 2023-01-06       A      250      266.666667
6 2023-01-07       B      100      216.666667
7 2023-01-08       B      150      166.666667
8 2023-01-09       A      200      150.000000
9 2023-01-10       B      300      216.666667

**Q16.** Find the top 2 highest revenue days for each product from `df_sales`.

In [50]:
top2=df_sales.sort_values(["Product","Revenue"],ascending=[True,False]).groupby("Product").head(2)
print(top2)

        Date Product  Revenue  Rolling_Avg_3D
4 2023-01-05       A      300      233.333333
5 2023-01-06       A      250      266.666667
9 2023-01-10       B      300      216.666667
3 2023-01-04       B      250      200.000000

**Q17.** Extract the year and month from the 'Date' column in `df_sales` and create two new columns 'Year' and 'Month'.

In [51]:
df_sales["year"]=df_sales["Date"].dt.year
df_sales["month"]=df_sales["Date"].dt.month
print(df_sales)

        Date Product  Revenue  Rolling_Avg_3D  year  month
0 2023-01-01       A      100             NaN  2023      1
1 2023-01-02       B      200             NaN  2023      1
2 2023-01-03       A      150      150.000000  2023      1
3 2023-01-04       B      250      200.000000  2023      1
4 2023-01-05       A      300      233.333333  2023      1
5 2023-01-06       A      250      266.666667  2023      1
6 2023-01-07       B      100      216.666667  2023      1
7 2023-01-08       B      150      166.666667  2023      1
8 2023-01-09       A      200      150.000000  2023      1
9 2023-01-10       B      300      216.666667  2023      1